;; am - A project template generated by ahungry-fleece
;; Copyright (C) 2018 Matthew Carter <m@ahungry.com>
;;
;; This program is free software: you can redistribute it and/or modify
;; it under the terms of the GNU Affero General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.
;;
;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU Affero General Public License for more details.
;;
;; You should have received a copy of the GNU Affero General Public License
;; along with this program.  If not, see <http://www.gnu.org/licenses/>.

;;;; am.lib.resolver.lisp

(in-package #:cl-user)

(defpackage am.lib.resolver
  (:use :cl
        :af.lib.hashy
        :af.lib.io)
  (:export
   :echo))

(in-package #:am.lib.resolver)

(defstruct node-package
  dev-dependencies
  dependencies
  version
  description
  name)

(defun json-file-to-node-package (file)
  "Load a JSON file to the object."
  (let ((hash (hash-from-json-file file)))
    (make-node-package
     :dev-dependencies (ref "#/devDependencies" hash)
     :dependencies (ref "#/dependencies" hash)
     :version (ref "#/version" hash)
     :description (ref "#/description" hash)
     :name (ref "#/name" hash))))


(defun extract-tarball (pathname)
  "Extract a tarball (.tar.gz) file to a directory (*default-pathname-defaults*)."
  (with-open-file (tarball-stream pathname
                                  :direction :input
                                  :element-type '(unsigned-byte 8))
    (archive::extract-files-from-archive
     (archive:open-archive 'archive:tar-archive
                           (chipz:make-decompressing-stream 'chipz:gzip tarball-stream)
                                 :direction :input))))

(defun echo (input)
  input)

;;; "am.lib.resolver" goes here. Hacks and glory await!
